name: Test Python Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t cleanup-test .

      - name: Run container with default interval (24h)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            cleanup-test

      - name: Run container with custom interval (12h)
        run: |
          docker run --rm \
            -e CLEANUP_INTERVAL=12h \
            -v /var/run/docker.sock:/var/run/docker.sock \
            cleanup-test
